---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  use_sudo: true

provisioner:
  name: dokken
  deprecations_as_errors: true
#  name: chef_zero
  # Allow the chef-vault to resolve
  data_bags_path: "test/fixtures/data_bags"
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

transport:
  name: dokken

verifier:
  name: inspec
  # root_path: '/opt/verifier'
  # sudo: false

platforms:
#  - name: ubuntu-16.04
  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN mkdir -p /data/splunk-test
        # Disable file locking check by Splunk as it fails on unsupported file systems used in some Docker hosts (e.g. on Mac)
        - RUN mkdir -p /opt/splunk/etc
        - RUN printf '
          SPLUNK_SERVER_NAME=Splunkd\n
          SLPUNK_WEB_NAME=splunkweb\n
          OPTIMISTIC_ABOUT_FILE_LOCKING=1\n' > /opt/splunk/etc/splunk-launch.conf

suites:
  - name: default
    run_list:
      - recipe[perficient_splunk::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      dev_mode: true
      splunk:
        accept_license: true

  - name: server
    run_list:
      - recipe[perficient_splunk::server]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      dev_mode: true
      splunk:
        accept_license: true

  - name: client
    run_list:
      - recipe[perficient_splunk::client]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
        is_server: false
